### ISSUE TITLE
[bug] 발견한 버그 목록

### ISSUE THREAD

**Issue by kimisadev27** [Dev-FE-1/Toy_Project_3_Team5#143]
#### 1. 플레이리스트 수정페이지
- [x] 1. 영상목록 누락

#### 2. 플레이리스트 상세페이지
- [ ] 1. 불러올때마다 영상 순서가 바뀜 (#149)
- [ ] 2. 팔로우 버튼 누르면 우상단 프로필이미지가 초기화됨
- [ ] 3. 로그인 안해도 댓글이 달리고, 그 댓글 삭제가 가능함 (#149)
- [ ] 4. 다른사람 채널에 댓글달면 프로필 안나옴 (#149)
![Sep-07-2024 11-27-05](https://github.com/user-attachments/assets/3faf251b-5518-4fff-8cb2-83bbafe3682b)
- [ ] 5. 본인 플리일때 팔로우버튼 표시 (#149)

#### 3. 마이플리 페이지(홈)
- [x] 플리 삭제 시 실시간 업데이트 안됨

### 💻 버그 시뮬레이션

1.1. 플레이리스트 수정 페이지 접근시 발생

2.3. userId가 '' 빈값으로 데이터가 db에 저장됨. 로그인 체크 필요

### 📄 수정 내역

1.1. 영상목록 불러오는 함수 수정

2.4. 프로필 수정페이지에서 등록하는 프로필이미지에 대한 처리를 변경할 예정

### 📝 메모

발견하는대로 계속 추가 예정입니다.

#### 플레이리스트 상세페이지
- [ ] 1. 댓글추가 로그인유무 체크 (추가기능)
- [ ] 2. 팔로우 버튼 누르면 로그인하겠습니까 - 모달 띄우기 (추가기능)

**Comment by kimisadev27** [comment]
미사용으로 닫겠습니다~
